### ISSUE TITLE
WAV: PlayMusic - Unrecognized audio format

### ISSUE THREAD

**Issue by BeWorld2018** [libsdl-org/SDL_mixer#319]
Hi,
I have a problem with my SDL_Mixer (PPC MorphOS - plateform not official....)
Somes WAV sounds doesnt read with playmus (Mix_LoadMUS). (Unrecognized audio format)

I try to find the problem.. but i dont find, maybe endian  :-(
PS: return FALSE here : https://github.com/libsdl-org/SDL_mixer/blob/master/src/codecs/music_wav.c#L914

Work fines with 2.0.4....
Thanks for your help

[setup.zip](https://github.com/libsdl-org/SDL_mixer/files/6495786/setup.zip)

**Comment by sezero** [comment]
> I have a problem with my SDL_Mixer (PPC MorphOS - plateform not official....)
> Somes WAV sounds doesnt read with playmus (Mix_LoadMUS). (Unrecognized audio format)
> 
> I try to find the problem.. but i dont find, maybe endian :-(

It does _not_ seem like an endian issue: playwave loads it fine, but
playmus fails: The playwave example program calls Mix_LoadWAV_RW which,
in turn, calls SDL_LoadWAV_RW: an SDL call, not SDL_mixer. The playmus
example prog calls Mix_LoadMUS_RW -> WAV_CreateFromRW -> LoadWAVMusic
where it should be failing.

The wav in question is 8 bit, stereo 22050 Hz standart Microsoft WAV PCM.
It loads a 16 bit file fine, therefore the issue is with 8 bit??

@Wohlstand: You touched music_wav.c, please have a look.

> PS: return FALSE here : https://github.com/libsdl-org/SDL_mixer/blob/master/src/codecs/music_wav.c#L914

It already does that? Or am I misreading what you mean?

> Work fines with 2.0.4....

Yes, this is a regression.

**Comment by sezero** [comment]
No, I tried some other 8 bit files and they loaded fine. It seems to have an issue
with the attached setup.wav file.

**Comment by sezero** [comment]
> > PS: return FALSE here : https://github.com/libsdl-org/SDL_mixer/blob/master/src/codecs/music_wav.c#L914
> 
> It already does that? Or am I misreading what you mean?

OK, I finally got what you actually meant (I'm slow today): ParseLIST()
returns false, because the data read starts not with "INFO" but "adtl",

I think we should ignore whether we actually hit "INFO" and return true
always, like the following:
```diff
diff --git a/src/codecs/music_wav.c b/src/codecs/music_wav.c
index 461ecf0..8dd2a98 100644
--- a/src/codecs/music_wav.c
+++ b/src/codecs/music_wav.c
@@ -825,9 +825,8 @@ static void read_meta_field(Mix_MusicMetaTags *tags, Mix_MusicMetaTag tag_type,
 
 static SDL_bool ParseLIST(WAV_Music *wave, Uint32 chunk_length)
 {
-    SDL_bool loaded = SDL_FALSE;
-
     Uint8 *data;
+
     data = (Uint8 *)SDL_malloc(chunk_length);
     if (!data) {
         Mix_SetError("Out of memory");
@@ -857,13 +856,12 @@ static SDL_bool ParseLIST(WAV_Music *wave, Uint32 chunk_length)
             }
             i++;
         }
-        loaded = SDL_TRUE;
     }
 
     /* done: */
     SDL_free(data);
 
-    return loaded;
+    return SDL_TRUE;
 }
 
 static SDL_bool LoadWAVMusic(WAV_Music *wave)
```

Comments?

Also, the current code doesn't handle odd chunk lengths properly?
Needs handling?

**Comment by Wohlstand** [comment]
The problem is not the length, the tag itself, no idea what strange software had to create it, it's absolutely invalid or non-standard one.
![изображение](https://user-images.githubusercontent.com/6751442/118567441-79abda00-b77e-11eb-9825-88b156fe7c50.png)

I guess it's fine if such invalid tags will be just ignored if they don't contain any valid data. I had to polish the code on in most validly-generated data and on some minor set of weird files that I hadn't so much.

btw, just an example how LIST chunk should be formatted usually:
[woof-pcm.wav.gz](https://github.com/libsdl-org/SDL_mixer/files/6497389/woof-pcm.wav.gz)

![Снимок экрана от 2021-05-18 02-20-06](https://user-images.githubusercontent.com/6751442/118568080-bcba7d00-b77f-11eb-9530-bf24f9090b6a.png)

**Comment by Wohlstand** [comment]
@sezero, I applied your patch and tested it on my side, works fine. :+1: 
Yeah, I agree that any invalid content of the LIST chunk must be ignored.

**Comment by sezero** [comment]
I _think_ it may be created by cooledit and the actual chunk should be `cue`
See snd_mem.c:GetWavinfo() in quake source: https://github.com/id-Software/Quake/blob/master/WinQuake/snd_mem.c#L294

**Comment by Wohlstand** [comment]
I see, the "cue " is a thing earlier, weird one... :thinking:

**Comment by sezero** [comment]
> I see, the "cue " is a thing earlier, weird one... thinking

Possibly, yes, not familiar with much it myself. Although, looking at the
referenced quake source, `cue ` is expected to be followed by `LIST`,
so that's _possibly_ the issue we're facing here.

**Comment by sezero** [comment]
Anyways, I applied the patch as https://github.com/libsdl-org/SDL_mixer/commit/e8cfc9249c3a468b8a2ae29c0f6768d5c50b4e4e as an immediate fix.

Odd chunk lengths is a different issue which still need handling, though.

**Comment by BeWorld2018** [comment]
Arrf... i response after war lol.... but thanks you !!!
Solve my issue :-)
