### ISSUE TITLE
Use stb_vorbis instead of libogg and libvorbis

### ISSUE THREAD

**Issue by VinnyVicious** [libsdl-org/SDL_mixer#329]
Both `libogg` and `libvorbis` are huge dependencies and are complex to build across platforms, specially since their bundled `CMakeLists.txt` are obsolete and rarely updated. No compatibility with other popular build systems or package managers either. 

stb_vorbis is a much more portable and would be a great addition to SDL_Mixer.

**Comment by Wohlstand** [comment]
Some time ago I made the use of `stb_vorbis` on my form (MixerX) side:
- https://github.com/WohlSoft/SDL-Mixer-X/blob/master/src/codecs/music_ogg_stb.c
- https://github.com/WohlSoft/SDL-Mixer-X/tree/master/src/codecs/stb_vorbis

**Note:** At me the [modified version of stb_vorbis](https://github.com/WohlSoft/SDL-Mixer-X/commits/master/src/codecs/stb_vorbis/stb_vorbis.h), I made a lot of changes on it, because in its original form it doesn't properly work as a part of Mixer and fails to build on some platforms:
- I replaced all integer types with these are provided by SDL headers
- I replaced all StdC calls with SDL equivalents
- I implemented the SDL_RWops support natively, mainly because given read methods aren't suitable for the case
- I fixed the bug because of inaccurate positioning which is very sensitive for loop tags (reported by one of the users of my projects, and after investigation, I confirmed and fixed it, also I sent the patch to the original version)
- I replaced all C++ single-line comments with C90-friendly multiline comments.

**Comment by slouken** [comment]
Added, thanks!

**Comment by VinnyVicious** [comment]
Thank you!
