### ISSUE TITLE
VCRUNTIME140.dll dependency in SDL2_mixer.dll

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL_mixer#406]
due to the compiler option /MD and the use of memcpy and memset, including SDL2_mixer.dll will create a dependency on the visual studio run time DLLs, which isn't desirable. Either use SDL_memset / SDL_memcpy or /MT instead of /MD.

**Comment by AntTheAlchemist** [comment]
There are some "#define memset SDL_memset" type things that I guess should avoid this.  Something has been missed, or there's an implied memset / memcpy somewhere. A VC DLL dependency shouldn't be there either way.

**Comment by sezero** [comment]
Can you tell us which compiled object has the references needed from vc dll?

**Comment by AntTheAlchemist** [comment]
How can you analyse an .obj? This is a shot in the dark but I think the problem is native_midi and it happens when minwinbase.h is included and "#define CopyMemory RtlCopyMemory" expands to "#define RtlCopyMemory(Destination,Source,Length) memcpy((Destination),(Source),(Length))".

**Comment by sezero** [comment]
We don't use CopyMemory anywhere. Can you give us the preprocessed source of whichever object file's source?

**Comment by sezero** [comment]
The only use of CopyMemory I found is not in SDL_mixer, but in SDL's SDL_main:
https://github.com/libsdl-org/SDL/blob/main/src/main/windows/SDL_windows_main.c#L73
(And why the hell are we not using SDL_memcpy in there??)

... and SDL_main is not supposed to creep into SDL_mixer any way. Baffled..

**Comment by madebr** [comment]
Using [`dumpbin /IMPORTS`](https://docs.microsoft.com/en-us/cpp/build/reference/imports-dumpbin?view=msvc-170), you can figure out what symbols `SDL2_mixers.dll` import from each library.

**Comment by AntTheAlchemist** [comment]
The SDL2.dll I built in the same way and my project's .exe doesn't import any VC runtimes, which makes it more baffling.

**Comment by sezero** [comment]
Does the following change anything by any chance? (There may be other places like that in there,
this one caught my eye first.)
```diff
diff --git a/src/codecs/dr_libs/dr_flac.h b/src/codecs/dr_libs/dr_flac.h
index bd174c4..2316676 100644
--- a/src/codecs/dr_libs/dr_flac.h
+++ b/src/codecs/dr_libs/dr_flac.h
@@ -7844,7 +7844,7 @@ static drflac* drflac_open_with_metadata_private(drflac_read_proc onRead, drflac
     }
 
     if (pAllocationCallbacks != NULL) {
-        allocationCallbacks = *pAllocationCallbacks;
+        DRFLAC_COPY_MEMORY(&allocationCallbacks, pAllocationCallbacks, sizeof(allocationCallbacks));
         if (allocationCallbacks.onFree == NULL || (allocationCallbacks.onMalloc == NULL && allocationCallbacks.onRealloc == NULL)) {
             return NULL;    /* Invalid allocation callbacks. */
         }
```

**Comment by AntTheAlchemist** [comment]
> Does the following change anything by any chance?

That's not done it.

I have undefined all but the modplug libraries and am only getting a memset dependency now though.

**Comment by sezero** [comment]
As I said, it would make our lives easier with object file or object files really depend on libc calls. If you zip all those object files and give us, it would help.

**Comment by AntTheAlchemist** [comment]
[SDL2_mixer_obj.zip](https://github.com/libsdl-org/SDL_mixer/files/8847871/SDL2_mixer_obj.zip)

**Comment by sezero** [comment]
VC runtime dll dependency is _almost_ in all of the objects:
effect_position.obj, effects_internal.obj, load_aiff.obj,
load_voc.obj, mp3utils.obj, music.obj, music_drflac.obj,
music_drmp3.obj, music_modplug.obj, music_ogg_stb.obj,
music_opus.obj, music_timidity.obj, music_wav.obj, utils.obj
(maybe I missed some), and all of which are x86.

The most of the required symbols are `__fltused`, `__ftol2_sse`,
`___security_cookie`, and `@__security_check_cookie@4`.

And the following additionally require:
- music_ogg_stb: `___report_rangecheckfailure`
- mp3utils.obj: `___report_rangecheckfailure`, `__chkstk`
- music_drmp3.obj: `__chkstk`, `__aulldiv`
- music_drflac.obj: `__chkstk`, `__allmul`, `__allshr`
- music_wav.obj: `__allmul`, `__allrem`
- utils.obj: `__allmul`

SDL itself provides most (if not all) of such dependencies internally
therefore SDL2.dll doesn't depend on vc runtime dll, however SDL_mixer
doesn't provide them: Unless @slouken and @icculus does otherwise, the
temporary solution (at least) would be to statically linking to msvc
runtime.

**Comment by slouken** [comment]
> SDL itself provides most (if not all) of such dependencies internally therefore SDL2.dll doesn't depend on vc runtime dll, however SDL_mixer doesn't provide them: Unless @slouken and @icculus does otherwise, the temporary solution (at least) would be to statically linking to msvc runtime.

That's correct, the other SDL libraries have C runtime dependencies and you should build them with the version of Visual Studio that you're building your game with so they have the same runtime dependency. If you can't do that for some reason, or your game has no Visual C++ runtime dependency, you can use the official release binaries, which are built with mingw-64 to avoid that, or build with the static C++ runtime library.
