### ISSUE TITLE
vendored vorbis with cmake

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_mixer#522]
@madebr: Do we want this proposed patch in our fork? https://github.com/xiph/vorbis/pull/98

**Comment by madebr** [comment]
Fixed in SDL2_mixer: https://github.com/libsdl-org/SDL_mixer/commit/b08b52bc134b2c9c040390c5539c06c3378707ac
Fixed in SDL3_mixer: https://github.com/libsdl-org/SDL_mixer/commit/7127e9e1c137efab7a7643949ebd3d1b1ec1eaa5 + https://github.com/libsdl-org/SDL_mixer/commit/7321817a239260944ac1042d752e623bae9acf24
