### ISSUE TITLE
lots of "defined in the headers but not the wiki!" warnings

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_mixer#542]
E.g.: `WARNING: Mix_AllocateChannels defined in the headers but not the wiki!`
Seen in the CI logs too.

**Comment by slouken** [comment]
I think we need someone to go through and update the wiki with all of our changes.

Any volunteers?

**Comment by madebr** [comment]
These are caused by this line:
https://github.com/libsdl-org/SDL_mixer/blob/14f1eb25603cc75624e9d2c92a5b0eebcf93a015/.wikiheaders-options#L15
It is set to 0 in SDL, but to 1 in the satellite libraries.

I asked here: https://github.com/libsdl-org/SDL/issues/7514#issuecomment-1608560156 (but I don't think it got answered)

**Comment by madebr** [comment]
> I think we need someone to go through and update the wiki with all of our changes.
> 
> Any volunteers?

The manpage generator script always generates the wiki/man pages from scratch.
So when first generating the docs, all pages are guaranteed to be missing.

**Comment by slouken** [comment]
Oh, okay. So is it fine just to remove the warning?

**Comment by madebr** [comment]
I think the warning makes sense when updating the sdl wiki, but not when generating the headers.
So perhaps it should be changed into a cli argument-only option.

**Comment by sezero** [comment]
https://github.com/libsdl-org/SDL_mixer/pull/552 seems to have fixed this.

**Comment by sezero** [comment]
BTW, the SDL2 branch has the same `warn_about_missing = 1` but I don't remember getting the warnings.
